// lib/channels.ts

export interface ChannelItem {
  id: string;
  name: string;
  quality: '4K UHD' | 'FHD 60FPS' | 'HD';
  genre: string;
  language: string;
  epg: boolean;
  bitrate: string;
  currentProgram: string;
}

export interface ChannelCategory {
  slug: string;
  name: string;
  title: string;
  tagline: string;
  description: string;
  count: string;
  iconName: string;
  badge: string;
  channels: ChannelItem[];
}

export const channelCategories: ChannelCategory[] = [
  {
    slug: 'sports-ppv',
    name: 'Live Sports & PPV',
    title: 'Live Sports, Stadium Feeds & PPV Events',
    tagline: 'Uncompressed 60FPS Broadcast Streams with Zero Freezing',
    description: 'Direct high-bitrate satellite feeds covering the Premier League, UEFA Champions League, NFL Sunday Ticket, NBA League Pass, UFC Main Cards, Formula 1 4K, and Box Office PPVs with Anti-Freeze 9.0 multi-node routing.',
    count: '3,500+ Live Feeds',
    iconName: 'Trophy',
    badge: '4K 60FPS • Low Latency',
    channels: [
      { id: 'sp-1', name: 'Sky Sports Main Event 4K', quality: '4K UHD', genre: 'Football / Multi-Sport', language: 'English', epg: true, bitrate: '25 Mbps', currentProgram: 'Premier League Matchday Live' },
      { id: 'sp-2', name: 'Sky Sports Premier League UHD', quality: '4K UHD', genre: 'Premier League', language: 'English', epg: true, bitrate: '24 Mbps', currentProgram: 'Super Sunday Pre-Match' },
      { id: 'sp-3', name: 'Sky Sports Football HD', quality: 'FHD 60FPS', genre: 'EFL & Scottish Premiership', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'EFL Championship Live' },
      { id: 'sp-4', name: 'Sky Sports F1 4K UHD', quality: '4K UHD', genre: 'Motorsport 60FPS', language: 'English', epg: true, bitrate: '25 Mbps', currentProgram: 'Grand Prix Qualifying Live' },
      { id: 'sp-5', name: 'Sky Sports Cricket HD', quality: 'FHD 60FPS', genre: 'Cricket Live', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'International Test Series' },
      { id: 'sp-6', name: 'Sky Sports Golf HD', quality: 'FHD 60FPS', genre: 'PGA Tour & Majors', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'PGA Tour Round 3' },
      { id: 'sp-7', name: 'Sky Sports Tennis HD', quality: 'FHD 60FPS', genre: 'ATP & WTA World Tour', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'ATP Masters 1000 Live' },
      { id: 'sp-8', name: 'Sky Sports Racing HD', quality: 'HD', genre: 'Horse Racing', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'Live From The Racetrack' },
      { id: 'sp-9', name: 'TNT Sports 1 4K Ultimate', quality: '4K UHD', genre: 'UEFA Champions League', language: 'English', epg: true, bitrate: '25 Mbps', currentProgram: 'Champions League Live' },
      { id: 'sp-10', name: 'TNT Sports 2 HD', quality: 'FHD 60FPS', genre: 'European Football & Rugby', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Premiership Rugby Live' },
      { id: 'sp-11', name: 'TNT Sports 3 HD', quality: 'FHD 60FPS', genre: 'MotoGP & Combat', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'MotoGP Main Race' },
      { id: 'sp-12', name: 'TNT Sports 4 HD', quality: 'FHD 60FPS', genre: 'Combat Sports & Serie A', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Live Serie A Matchday' },
      { id: 'sp-13', name: 'ESPN HD USA Feed', quality: 'FHD 60FPS', genre: 'US Sports / NBA / NCAA', language: 'English', epg: true, bitrate: '15 Mbps', currentProgram: 'SportsCenter Live' },
      { id: 'sp-14', name: 'ESPN 2 HD USA', quality: 'FHD 60FPS', genre: 'College Football & Baseball', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'College Gameday Live' },
      { id: 'sp-15', name: 'ESPNU / ESPNews HD', quality: 'HD', genre: 'College Sports & Highlights', language: 'English', epg: true, bitrate: '10 Mbps', currentProgram: 'College Basketball Prime' },
      { id: 'sp-16', name: 'ESPN Deportes HD', quality: 'FHD 60FPS', genre: 'Latin American Sports', language: 'Spanish', epg: true, bitrate: '12 Mbps', currentProgram: 'Fútbol Picante' },
      { id: 'sp-17', name: 'NBC Sports Live Network', quality: 'FHD 60FPS', genre: 'Premier League & NFL', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Premier League Mornings' },
      { id: 'sp-18', name: 'Peacock Sports Live 1-8', quality: 'FHD 60FPS', genre: 'Exclusive Streaming Matches', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Simultaneous Matchday' },
      { id: 'sp-19', name: 'FOX Sports 1 (FS1) 4K', quality: '4K UHD', genre: 'MLB, MLS & World Cup', language: 'English', epg: true, bitrate: '22 Mbps', currentProgram: 'MLB on FOX Live' },
      { id: 'sp-20', name: 'FOX Sports 2 (FS2) HD', quality: 'FHD 60FPS', genre: 'Motorsport & Soccer', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'NASCAR Live Practice' },
      { id: 'sp-21', name: 'UFC Pay-Per-View Main Card 4K', quality: '4K UHD', genre: 'UFC Championship PPV', language: 'English', epg: true, bitrate: '25 Mbps', currentProgram: 'UFC World Title Bout' },
      { id: 'sp-22', name: 'UFC Fight Pass Live HD', quality: 'FHD 60FPS', genre: 'Prelims & Fight Library', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'UFC Early Prelims' },
      { id: 'sp-23', name: 'WWE Network 24/7 Live 4K', quality: '4K UHD', genre: 'Pro Wrestling & PPVs', language: 'English', epg: true, bitrate: '22 Mbps', currentProgram: 'Live WrestleMania / Royal Rumble' },
      { id: 'sp-24', name: 'DAZN 1 Bar HD UK', quality: 'FHD 60FPS', genre: 'World Boxing Championships', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Championship Fight Night' },
      { id: 'sp-25', name: 'DAZN 2 International HD', quality: 'FHD 60FPS', genre: 'European Football Leagues', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Matchday Review' },
      { id: 'sp-26', name: 'BeIN Sports Premium 1 4K', quality: '4K UHD', genre: 'La Liga & Ligue 1', language: 'Arabic/English', epg: true, bitrate: '25 Mbps', currentProgram: 'Studio El Clasico' },
      { id: 'sp-27', name: 'BeIN Sports Premium 2 HD', quality: 'FHD 60FPS', genre: 'Champions League Arab', language: 'Arabic', epg: true, bitrate: '14 Mbps', currentProgram: 'Live Match Analysis' },
      { id: 'sp-28', name: 'BeIN Sports English 1 HD', quality: 'FHD 60FPS', genre: 'Premier League EN Feed', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Saturday Kick-Off' },
      { id: 'sp-29', name: 'BeIN Sports English 2 HD', quality: 'FHD 60FPS', genre: 'European Football', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Ligue 1 Prime Match' },
      { id: 'sp-30', name: 'BeIN Sports French 1-3 Max', quality: 'FHD 60FPS', genre: 'French Football & Tennis', language: 'French', epg: true, bitrate: '14 Mbps', currentProgram: 'Le Grand Match' },
      { id: 'sp-31', name: 'NFL Game Pass / RedZone HD', quality: 'FHD 60FPS', genre: 'NFL Live RedZone', language: 'English', epg: true, bitrate: '15 Mbps', currentProgram: '7 Hours of Commercial-Free Football' },
      { id: 'sp-32', name: 'NFL Sunday Ticket Feeds 1-10', quality: 'FHD 60FPS', genre: 'Every Sunday Live Match', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Direct Stadium Game' },
      { id: 'sp-33', name: 'NBA League Pass HD 1-12', quality: 'FHD 60FPS', genre: 'Full NBA Season Coverage', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Live NBA Primetime Match' },
      { id: 'sp-34', name: 'MLB Extra Innings 1-8 HD', quality: 'FHD 60FPS', genre: 'Major League Baseball', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Live Ballpark Feed' },
      { id: 'sp-35', name: 'NHL Center Ice 1-8 HD', quality: 'FHD 60FPS', genre: 'NHL Hockey Live', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Stanley Cup Playoffs' },
      { id: 'sp-36', name: 'Astro SuperSport 1-4 UHD', quality: '4K UHD', genre: 'Asian International Sports', language: 'English', epg: true, bitrate: '20 Mbps', currentProgram: 'BWF Badminton World Tour' },
      { id: 'sp-37', name: 'Canal+ Foot 4K (France)', quality: '4K UHD', genre: 'UEFA & Ligue 1', language: 'French', epg: true, bitrate: '22 Mbps', currentProgram: 'Soir de Champions League' },
      { id: 'sp-38', name: 'Canal+ Sport 360 HD', quality: 'FHD 60FPS', genre: 'Motorsports & Rugby Top 14', language: 'French', epg: true, bitrate: '14 Mbps', currentProgram: 'Top 14 Rugby Live' },
      { id: 'sp-39', name: 'Movistar LaLiga 1-4 UHD (ES)', quality: '4K UHD', genre: 'Spanish Primera Division', language: 'Spanish', epg: true, bitrate: '24 Mbps', currentProgram: 'El Gran Derbi Live' },
      { id: 'sp-40', name: 'Movistar Liga de Campeones 4K', quality: '4K UHD', genre: 'Champions League Spain', language: 'Spanish', epg: true, bitrate: '24 Mbps', currentProgram: 'Noche de Campeones' },
      { id: 'sp-41', name: 'Sky Sport Bundesliga 1-10 (DE)', quality: 'FHD 60FPS', genre: 'German Bundesliga', language: 'German', epg: true, bitrate: '15 Mbps', currentProgram: 'Bundesliga Konferenz Live' },
      { id: 'sp-42', name: 'Sky Sport Top Event UHD (DE)', quality: '4K UHD', genre: 'Top European Sports', language: 'German', epg: true, bitrate: '24 Mbps', currentProgram: 'Der Klassiker Live' },
      { id: 'sp-43', name: 'Sky Sport F1 HD (DE)', quality: 'FHD 60FPS', genre: 'Formula 1 German Feed', language: 'German', epg: true, bitrate: '14 Mbps', currentProgram: 'Formel 1 Rennen Live' },
      { id: 'sp-44', name: 'Sky Sport Uno 4K (Italy)', quality: '4K UHD', genre: 'Serie A & Champions League', language: 'Italian', epg: true, bitrate: '24 Mbps', currentProgram: 'Diretta Serie A TIM' },
      { id: 'sp-45', name: 'Sky Sport Calcio HD (Italy)', quality: 'FHD 60FPS', genre: 'Italian Calcio Live', language: 'Italian', epg: true, bitrate: '14 Mbps', currentProgram: 'Serie A Show' },
      { id: 'sp-46', name: 'Sport TV 1-6 HD (Portugal)', quality: 'FHD 60FPS', genre: 'Primeira Liga & UEFA', language: 'Portuguese', epg: true, bitrate: '14 Mbps', currentProgram: 'Liga Portugal Em Direto' },
      { id: 'sp-47', name: 'TSN 1-5 HD (Canada)', quality: 'FHD 60FPS', genre: 'Canadian Live Sports', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'CFL & NHL Live' },
      { id: 'sp-48', name: 'Sportsnet National 4K (CA)', quality: '4K UHD', genre: 'NHL Hockey Night & Blue Jays', language: 'English', epg: true, bitrate: '22 Mbps', currentProgram: 'Hockey Night in Canada' },
      { id: 'sp-49', name: 'Optus Sport 1-6 HD (Australia)', quality: 'FHD 60FPS', genre: 'Premier League Australia', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Matchday Premier Australia' },
      { id: 'sp-50', name: 'SuperSport Premier League (SA)', quality: '4K UHD', genre: 'African Continental Sports', language: 'English', epg: true, bitrate: '22 Mbps', currentProgram: 'Saturday Big Match Live' },
      { id: 'sp-51', name: 'Star Sports 1 & Select HD', quality: 'HD', genre: 'Cricket IPL & ICC World Cup', language: 'Hindi/English', epg: true, bitrate: '10 Mbps', currentProgram: 'IPL Live Match' },
      { id: 'sp-52', name: 'Matchroom Boxing VIP PPV', quality: '4K UHD', genre: 'World Heavyweight Boxing', language: 'English', epg: true, bitrate: '25 Mbps', currentProgram: 'World Title Main Event' },
    ],
  },
  {
    slug: 'usa-canada',
    name: 'USA & Canada Feeds',
    title: 'USA & Canada Local/National Networks',
    tagline: 'Complete North American Live TV Lineup with 7-Day EPG',
    description: 'Stream all major East/West US network feeds, regional sports affiliates, breaking 24/7 news, premium cinema multiplexes, and complete Canadian lineups in native 1080p and 4K resolution.',
    count: '4,800+ Channels',
    iconName: 'Tv',
    badge: '7-Day EPG Synced',
    channels: [
      { id: 'us-1', name: 'HBO East / West 4K UHD', quality: '4K UHD', genre: 'Prestige Cinema & Series', language: 'English', epg: true, bitrate: '22 Mbps', currentProgram: 'House of the Dragon 4K' },
      { id: 'us-2', name: 'HBO 2 & HBO Signature HD', quality: 'FHD 60FPS', genre: 'Cinema & Award Winners', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Blockbuster Feature Film' },
      { id: 'us-3', name: 'HBO Family & HBO Comedy HD', quality: 'FHD 60FPS', genre: 'Comedy & Family Movies', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Family Movie Night' },
      { id: 'us-4', name: 'Showtime East / West 4K', quality: '4K UHD', genre: 'Premium Hollywood Movies', language: 'English', epg: true, bitrate: '20 Mbps', currentProgram: 'Championship Boxing & Movies' },
      { id: 'us-5', name: 'Showtime 2 & Showcase HD', quality: 'FHD 60FPS', genre: 'Cinema Vault', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Original Drama Series' },
      { id: 'us-6', name: 'Starz & Starz Edge 4K', quality: '4K UHD', genre: 'Hollywood Blockbusters', language: 'English', epg: true, bitrate: '20 Mbps', currentProgram: 'Power Universe Series' },
      { id: 'us-7', name: 'Starz Cinema & Starz Kids HD', quality: 'FHD 60FPS', genre: 'Cinema & Family', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Animated Feature Film' },
      { id: 'us-8', name: 'Cinemax / MoreMax / ActionMax', quality: 'FHD 60FPS', genre: 'Action & Thrillers', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Action Movie Marathon' },
      { id: 'us-9', name: 'ABC East (WABC New York) HD', quality: 'FHD 60FPS', genre: 'National Primetime', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Good Morning America & Primetime' },
      { id: 'us-10', name: 'ABC West (KABC Los Angeles) HD', quality: 'FHD 60FPS', genre: 'West Coast Primetime', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Primetime Drama Lineup' },
      { id: 'us-11', name: 'NBC East (WNBC New York) HD', quality: 'FHD 60FPS', genre: 'National Broadcast', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'The Today Show & Nightly News' },
      { id: 'us-12', name: 'NBC West (KNBC Los Angeles) HD', quality: 'FHD 60FPS', genre: 'West Coast Broadcast', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Sunday Night Football / Primetime' },
      { id: 'us-13', name: 'CBS East (WCBS New York) HD', quality: 'FHD 60FPS', genre: 'National Primetime', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'CBS Mornings & 60 Minutes' },
      { id: 'us-14', name: 'CBS West (KCBS Los Angeles) HD', quality: 'FHD 60FPS', genre: 'West Coast Primetime', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'NFL on CBS & Primetime' },
      { id: 'us-15', name: 'FOX East (WNYW New York) HD', quality: 'FHD 60FPS', genre: 'National Primetime & Sports', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'FOX NFL Sunday & Primetime' },
      { id: 'us-16', name: 'FOX West (KTTV Los Angeles) HD', quality: 'FHD 60FPS', genre: 'West Coast Primetime', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Animation Domination' },
      { id: 'us-17', name: 'The CW Network HD', quality: 'HD', genre: 'Teen Drama & Sci-Fi', language: 'English', epg: true, bitrate: '10 Mbps', currentProgram: 'Primetime Drama' },
      { id: 'us-18', name: 'CNN USA Live HD', quality: 'HD', genre: '24/7 Breaking News', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'The Situation Room' },
      { id: 'us-19', name: 'Fox News Channel HD', quality: 'HD', genre: '24/7 News & Opinion', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'The Five & Primetime' },
      { id: 'us-20', name: 'MSNBC Live HD', quality: 'HD', genre: 'Political News & Analysis', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'Morning Joe & Rachel Maddow' },
      { id: 'us-21', name: 'CNBC Live Business HD', quality: 'HD', genre: 'Stock Market & Finance', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'Squawk on the Street' },
      { id: 'us-22', name: 'Bloomberg Television HD', quality: 'HD', genre: 'Global Markets & Crypto', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'Bloomberg Markets Live' },
      { id: 'us-23', name: 'Discovery Channel HD', quality: 'FHD 60FPS', genre: 'Science & Exploration', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Deadliest Catch' },
      { id: 'us-24', name: 'History Channel HD', quality: 'FHD 60FPS', genre: 'History & Factual', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'The Curse of Oak Island' },
      { id: 'us-25', name: 'National Geographic HD', quality: 'FHD 60FPS', genre: 'Nature & Adventure', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Life Below Zero' },
      { id: 'us-26', name: 'Nat Geo Wild 4K UHD', quality: '4K UHD', genre: 'Wildlife in 4K', language: 'English', epg: true, bitrate: '22 Mbps', currentProgram: 'Predators of the Serengeti' },
      { id: 'us-27', name: 'Animal Planet HD', quality: 'HD', genre: 'Wildlife & Pets', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'River Monsters' },
      { id: 'us-28', name: 'AMC HD (American Movie Classics)', quality: 'FHD 60FPS', genre: 'Drama & Horror Series', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'The Walking Dead Universe' },
      { id: 'us-29', name: 'FX & FXX HD', quality: 'FHD 60FPS', genre: 'Critically Acclaimed Comedy', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'It\'s Always Sunny in Philadelphia' },
      { id: 'us-30', name: 'USA Network HD', quality: 'FHD 60FPS', genre: 'WWE Raw & Dramas', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'WWE Monday Night Raw' },
      { id: 'us-31', name: 'TBS & TNT USA HD', quality: 'FHD 60FPS', genre: 'NBA on TNT & Comedy', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Inside the NBA Live' },
      { id: 'us-32', name: 'Bravo HD USA', quality: 'FHD 60FPS', genre: 'Reality & Pop Culture', language: 'English', epg: true, bitrate: '10 Mbps', currentProgram: 'The Real Housewives' },
      { id: 'us-33', name: 'TLC & HGTV HD', quality: 'FHD 60FPS', genre: 'Lifestyle & Home Renovation', language: 'English', epg: true, bitrate: '10 Mbps', currentProgram: 'Fixer Upper & Property Brothers' },
      { id: 'us-34', name: 'Food Network & Cooking Channel', quality: 'FHD 60FPS', genre: 'Culinary Competitions', language: 'English', epg: true, bitrate: '10 Mbps', currentProgram: 'Chopped & Diners, Drive-Ins' },
      { id: 'us-35', name: 'Comedy Central HD', quality: 'FHD 60FPS', genre: 'Standup & Satire', language: 'English', epg: true, bitrate: '10 Mbps', currentProgram: 'South Park & The Daily Show' },
      { id: 'us-36', name: 'MTV & VH1 Music HD', quality: 'HD', genre: 'Music & Reality', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'The Challenge & Ridiculousness' },
      { id: 'us-37', name: 'Disney Channel & Disney XD', quality: 'HD', genre: 'Kids & Family', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'Original Animated Series' },
      { id: 'us-38', name: 'Nickelodeon & Nicktoons HD', quality: 'HD', genre: 'Cartoons & Youth', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'SpongeBob SquarePants' },
      { id: 'us-39', name: 'Cartoon Network & Adult Swim', quality: 'FHD 60FPS', genre: 'Animation & Adult Swim', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Rick and Morty' },
      { id: 'us-40', name: 'Paramount Network HD', quality: 'FHD 60FPS', genre: 'Yellowstone & Westerns', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Yellowstone Primetime' },
      { id: 'us-41', name: 'Syfy & E! Entertainment HD', quality: 'HD', genre: 'Sci-Fi & Hollywood News', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'Original Sci-Fi Series' },
      { id: 'us-42', name: 'Bally Sports Regional 1-12 HD', quality: 'FHD 60FPS', genre: 'Regional NBA / NHL / MLB', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Local Live Game' },
      { id: 'us-43', name: 'YES Network (Yankees & Nets)', quality: 'FHD 60FPS', genre: 'New York Sports', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'New York Yankees Live' },
      { id: 'us-44', name: 'NESN (Red Sox & Bruins)', quality: 'FHD 60FPS', genre: 'Boston Sports', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Boston Red Sox Baseball' },
      { id: 'us-45', name: 'TSN 1, 2, 3, 4, 5 (Canada)', quality: 'FHD 60FPS', genre: 'Canadian Live Sports', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'CFL, NHL & Formula 1' },
      { id: 'us-46', name: 'Sportsnet Ontario & East (CA)', quality: 'FHD 60FPS', genre: 'Toronto Blue Jays & NHL', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Blue Jays Live Baseball' },
      { id: 'us-47', name: 'Sportsnet West & Pacific (CA)', quality: 'FHD 60FPS', genre: 'NHL Edmonton & Vancouver', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'NHL Regional Live' },
      { id: 'us-48', name: 'CBC National HD (Canada)', quality: 'FHD 60FPS', genre: 'Canadian Public Broadcast', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'The National & CBC News' },
      { id: 'us-49', name: 'CTV & Global TV HD (Canada)', quality: 'FHD 60FPS', genre: 'Canadian Primetime', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Primetime Hits & News' },
      { id: 'us-50', name: 'TVA & RDS Sports (Quebec)', quality: 'FHD 60FPS', genre: 'French Canadian Broadcast', language: 'French', epg: true, bitrate: '12 Mbps', currentProgram: 'Canadiens de Montréal Live' },
    ],
  },
  {
    slug: 'uk-ireland',
    name: 'UK & Ireland',
    title: 'UK & Ireland Complete Broadcast Bouquets',
    tagline: 'High-Bitrate Direct Feeds with BBC iPlayer & Sky Integration',
    description: 'Direct low-latency streams from London and Dublin servers. Watch all BBC, ITV, Channel 4 regions, Sky Cinema, and Irish RTÉ channels with ultra-fast zapping times.',
    count: '3,200+ Channels',
    iconName: 'Globe',
    badge: 'Low Latency UK Feeds',
    channels: [
      { id: 'uk-1', name: 'BBC One 4K / UHD London', quality: '4K UHD', genre: 'Public National Network', language: 'English', epg: true, bitrate: '22 Mbps', currentProgram: 'Strictly Come Dancing / Drama' },
      { id: 'uk-2', name: 'BBC One Regions (Scotland, Wales, NI)', quality: 'FHD 60FPS', genre: 'Regional Public Broadcast', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'BBC Regional News' },
      { id: 'uk-3', name: 'BBC Two HD Live', quality: 'FHD 60FPS', genre: 'Documentaries & Factual', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'University Challenge & Horizon' },
      { id: 'uk-4', name: 'BBC Three & BBC Four HD', quality: 'FHD 60FPS', genre: 'Youth & Arts Programming', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Documentary Masterpiece' },
      { id: 'uk-5', name: 'BBC News 24/7 HD', quality: 'HD', genre: 'Rolling International News', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'BBC News at Ten' },
      { id: 'uk-6', name: 'CBBC & CBeebies HD', quality: 'HD', genre: 'Kids & Toddlers Programming', language: 'English', epg: true, bitrate: '8 Mbps', currentProgram: 'Bedtime Stories & Blue Peter' },
      { id: 'uk-7', name: 'BBC Parliament HD', quality: 'HD', genre: 'Live Parliamentary Debates', language: 'English', epg: true, bitrate: '7 Mbps', currentProgram: 'House of Commons Live' },
      { id: 'uk-8', name: 'ITV 1 HD (London / Meridian)', quality: 'FHD 60FPS', genre: 'Commercial National TV', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Coronation Street & Emmerdale' },
      { id: 'uk-9', name: 'ITV 1 Regional Variants (Granada / Tyne)', quality: 'FHD 60FPS', genre: 'Regional Commercial Feeds', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Regional ITV News' },
      { id: 'uk-10', name: 'ITV 2 HD Live', quality: 'FHD 60FPS', genre: 'Reality & Sitcoms', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Love Island & Comedy' },
      { id: 'uk-11', name: 'ITV 3 HD Live', quality: 'FHD 60FPS', genre: 'Classic British Crime Drama', language: 'English', epg: true, bitrate: '10 Mbps', currentProgram: 'Midsomer Murders & Poirot' },
      { id: 'uk-12', name: 'ITV 4 HD Live', quality: 'FHD 60FPS', genre: 'Action Movies & Sports', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Live Snooker & Darts' },
      { id: 'uk-13', name: 'ITVBe HD Live', quality: 'HD', genre: 'Lifestyle & Reality UK', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'The Only Way Is Essex' },
      { id: 'uk-14', name: 'Channel 4 HD Live London', quality: 'FHD 60FPS', genre: 'British Drama & Comedy', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'The Great British Bake Off' },
      { id: 'uk-15', name: 'More4 HD Live', quality: 'FHD 60FPS', genre: 'Factual & Architecture', language: 'English', epg: true, bitrate: '10 Mbps', currentProgram: 'Grand Designs & Location' },
      { id: 'uk-16', name: 'Film4 HD UK', quality: 'FHD 60FPS', genre: 'Cinema & Indie Films', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Hollywood Prime Movie' },
      { id: 'uk-17', name: 'E4 HD Live', quality: 'FHD 60FPS', genre: 'Comedy & Youth Culture', language: 'English', epg: true, bitrate: '10 Mbps', currentProgram: 'The Big Bang Theory' },
      { id: 'uk-18', name: '4seven HD', quality: 'HD', genre: 'Channel 4 Best Highlights', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'Gogglebox Catch-up' },
      { id: 'uk-19', name: 'Channel 5 HD UK', quality: 'FHD 60FPS', genre: 'Entertainment & Factual', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'All Creatures Great and Small' },
      { id: 'uk-20', name: '5USA & 5Select HD', quality: 'HD', genre: 'US Crime & Documentaries', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'NCIS & Law and Order' },
      { id: 'uk-21', name: '5Action HD', quality: 'HD', genre: 'Action Cinema & Shows', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'Action Movie Special' },
      { id: 'uk-22', name: 'Sky Atlantic 4K UHD', quality: '4K UHD', genre: 'Exclusive HBO Dramas', language: 'English', epg: true, bitrate: '22 Mbps', currentProgram: 'Succession & The Last of Us' },
      { id: 'uk-23', name: 'Sky Max 4K UHD', quality: '4K UHD', genre: 'Blockbuster Entertainment', language: 'English', epg: true, bitrate: '20 Mbps', currentProgram: 'Original British Sci-Fi' },
      { id: 'uk-24', name: 'Sky Showcase HD', quality: 'FHD 60FPS', genre: 'Best of Sky TV', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Primetime Showcase' },
      { id: 'uk-25', name: 'Sky Witness HD', quality: 'FHD 60FPS', genre: 'US Police & Medical Drama', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Grey\'s Anatomy & Chicago Fire' },
      { id: 'uk-26', name: 'Sky Documentaries 4K', quality: '4K UHD', genre: 'Premium Factual in 4K', language: 'English', epg: true, bitrate: '20 Mbps', currentProgram: 'Sky Original Feature Doc' },
      { id: 'uk-27', name: 'Sky Nature 4K UHD', quality: '4K UHD', genre: 'Natural History 4K', language: 'English', epg: true, bitrate: '22 Mbps', currentProgram: 'Predators in Ultra HD' },
      { id: 'uk-28', name: 'Sky Crime HD Live', quality: 'FHD 60FPS', genre: 'True Crime & Investigation', language: 'English', epg: true, bitrate: '10 Mbps', currentProgram: 'Cold Case Files UK' },
      { id: 'uk-29', name: 'Sky Comedy HD Live', quality: 'FHD 60FPS', genre: 'US & UK Sitcoms', language: 'English', epg: true, bitrate: '10 Mbps', currentProgram: 'Curb Your Enthusiasm' },
      { id: 'uk-30', name: 'Sky Arts HD Live', quality: 'FHD 60FPS', genre: 'Music, Theatre & Fine Arts', language: 'English', epg: true, bitrate: '10 Mbps', currentProgram: 'Live at the Royal Albert Hall' },
      { id: 'uk-31', name: 'Sky Cinema Premiere 4K', quality: '4K UHD', genre: 'New Box Office Releases', language: 'English', epg: true, bitrate: '24 Mbps', currentProgram: 'Latest Theatrical Premiere' },
      { id: 'uk-32', name: 'Sky Cinema Action 4K', quality: '4K UHD', genre: 'Action, Thrillers & Marvel', language: 'English', epg: true, bitrate: '22 Mbps', currentProgram: 'Mission Impossible 4K' },
      { id: 'uk-33', name: 'Sky Cinema Comedy HD', quality: 'FHD 60FPS', genre: 'Comedy Movies', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Classic Comedy Hits' },
      { id: 'uk-34', name: 'Sky Cinema Drama HD', quality: 'FHD 60FPS', genre: 'Oscar Winning Cinema', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Award Winning Feature' },
      { id: 'uk-35', name: 'Sky Cinema Sci-Fi / Horror HD', quality: 'FHD 60FPS', genre: 'Sci-Fi & Cult Horror', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Alien Universe Marathon' },
      { id: 'uk-36', name: 'Sky Cinema Hits HD', quality: 'FHD 60FPS', genre: 'Hollywood Favorites', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'Top 50 Cinema Hits' },
      { id: 'uk-37', name: 'Gold HD UK', quality: 'FHD 60FPS', genre: 'Classic British Sitcoms', language: 'English', epg: true, bitrate: '10 Mbps', currentProgram: 'Only Fools and Horses' },
      { id: 'uk-38', name: 'Dave HD Live', quality: 'FHD 60FPS', genre: 'Panel Shows & Standup', language: 'English', epg: true, bitrate: '10 Mbps', currentProgram: 'Taskmaster & QI XL' },
      { id: 'uk-39', name: 'W Channel & Drama HD', quality: 'HD', genre: 'UK Dramas & Lifestyle', language: 'English', epg: true, bitrate: '9 Mbps', currentProgram: 'Call the Midwife' },
      { id: 'uk-40', name: 'Alibi HD Live', quality: 'FHD 60FPS', genre: 'British Murder Mysteries', language: 'English', epg: true, bitrate: '10 Mbps', currentProgram: 'Death in Paradise' },
      { id: 'uk-41', name: 'Sky News UK 4K', quality: '4K UHD', genre: '24/7 Rolling News', language: 'English', epg: true, bitrate: '18 Mbps', currentProgram: 'The UK Tonight Live' },
      { id: 'uk-42', name: 'GB News HD', quality: 'HD', genre: 'British News & Debate', language: 'English', epg: true, bitrate: '8 Mbps', currentProgram: 'Tonight with Andrew Neil' },
      { id: 'uk-43', name: 'RTÉ One HD (Ireland)', quality: 'FHD 60FPS', genre: 'Irish Public Broadcaster', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'The Late Late Show & News' },
      { id: 'uk-44', name: 'RTÉ2 HD (Ireland)', quality: 'FHD 60FPS', genre: 'GAA & European Sports', language: 'English', epg: true, bitrate: '14 Mbps', currentProgram: 'Live GAA Championship' },
      { id: 'uk-45', name: 'Virgin Media One HD (Ireland)', quality: 'FHD 60FPS', genre: 'Irish Commercial Entertainment', language: 'English', epg: true, bitrate: '12 Mbps', currentProgram: 'The Tonight Show Ireland' },
      { id: 'uk-46', name: 'Virgin Media Two & Three (IE)', quality: 'HD', genre: 'Irish Sports & Dramas', language: 'English', epg: true, bitrate: '10 Mbps', currentProgram: 'Champions League Live IE' },
      { id: 'uk-47', name: 'TG4 HD (Irish Language)', quality: 'HD', genre: 'Gaelic Culture & GAA', language: 'Irish/English', epg: true, bitrate: '9 Mbps', currentProgram: 'Gaelic Football Live' },
      { id: 'uk-48', name: 'RTÉ News Now (Ireland)', quality: 'HD', genre: 'Irish Rolling News', language: 'English', epg: true, bitrate: '8 Mbps', currentProgram: 'Six One News Live' },
      { id: 'uk-49', name: 'S4C HD (Wales)', quality: 'HD', genre: 'Welsh Language Programming', language: 'Welsh/English', epg: true, bitrate: '8 Mbps', currentProgram: 'Welsh Rugby Live' },
      { id: 'uk-50', name: 'BBC Alba HD (Scotland)', quality: 'HD', genre: 'Scottish Gaelic Broadcast', language: 'Gaelic/English', epg: true, bitrate: '8 Mbps', currentProgram: 'Scottish Premiership Live' },
    ],
  },
  {
    slug: 'movies-vod',
    name: '4K Movies & VOD Series',
    title: 'On-Demand 4K Cinema & Complete TV Box Sets',
    tagline: 'Updated Daily with Multi-Language Subtitles & Mastered Audio',
    description: 'Instant on-demand streaming for over 65,000 titles. Browse new 2026 theatrical cinema releases, Netflix original series, HBO prestige box sets, Disney+ 4K remasters, and all-time classic cinema with dual audio tracks.',
    count: '65,000+ Titles',
    iconName: 'Film',
    badge: 'Daily Server Refresh',
    channels: [
      { id: 'vod-1', name: '2026 Theatrical Cinema Premieres 4K', quality: '4K UHD', genre: 'Box Office Hits', language: 'Multi-Audio', epg: false, bitrate: '32 Mbps', currentProgram: 'Latest Theatrical Box Office Releases' },
      { id: 'vod-2', name: 'Netflix Original Series Complete Vault', quality: '4K UHD', genre: 'Binge-Worthy Series', language: 'Multi-Sub', epg: false, bitrate: '28 Mbps', currentProgram: 'Stranger Things & Wednesday (All Seasons)' },
      { id: 'vod-3', name: 'HBO Max Prestige Boxset Collection', quality: '4K UHD', genre: 'Prestige TV Drama', language: 'English', epg: false, bitrate: '28 Mbps', currentProgram: 'Game of Thrones & The Sopranos 4K' },
      { id: 'vod-4', name: 'Disney+ & Marvel Cinematic Universe', quality: '4K UHD', genre: 'Superheroes & Star Wars', language: 'Multi-Audio', epg: false, bitrate: '30 Mbps', currentProgram: 'The Mandalorian & Avengers 4K HDR' },
      { id: 'vod-5', name: 'Amazon Prime 4K HDR Series Hub', quality: '4K UHD', genre: 'Action & Sci-Fi Originals', language: 'Multi-Sub', epg: false, bitrate: '26 Mbps', currentProgram: 'The Boys & Rings of Power' },
      { id: 'vod-6', name: 'Apple TV+ High-Bitrate 4K Vault', quality: '4K UHD', genre: 'Award Winning Dramas', language: 'English', epg: false, bitrate: '35 Mbps', currentProgram: 'Ted Lasso & Severance in 4K HDR' },
      { id: 'vod-7', name: 'IMDb Top 250 Cinema Masterpieces', quality: '4K UHD', genre: 'All-Time Greatest Films', language: 'English', epg: false, bitrate: '25 Mbps', currentProgram: 'The Godfather & Pulp Fiction 4K' },
      { id: 'vod-8', name: 'Paramount+ & Showtime Series Vault', quality: '4K UHD', genre: 'Crime & Westerns', language: 'English', epg: false, bitrate: '25 Mbps', currentProgram: 'Yellowstone, Tulsa King & 1923' },
      { id: 'vod-9', name: 'Hulu & FX Complete Collections', quality: 'FHD 60FPS', genre: 'Comedy & Drama', language: 'English', epg: false, bitrate: '16 Mbps', currentProgram: 'The Bear & Shogun (Full Seasons)' },
      { id: 'vod-10', name: 'Peacock Originals & NBC Classics', quality: 'FHD 60FPS', genre: 'Sitcoms & Drama', language: 'English', epg: false, bitrate: '16 Mbps', currentProgram: 'The Office & Parks and Rec Remastered' },
      { id: 'vod-11', name: 'Hollywood Action & Sci-Fi 4K Vault', quality: '4K UHD', genre: 'Blockbuster Action', language: 'Multi-Audio', epg: false, bitrate: '30 Mbps', currentProgram: 'John Wick & Matrix 4K Collections' },
      { id: 'vod-12', name: 'Hollywood Thriller & Horror 4K', quality: '4K UHD', genre: 'Psychological & Horror', language: 'English', epg: false, bitrate: '25 Mbps', currentProgram: 'The Conjuring & A Quiet Place 4K' },
      { id: 'vod-13', name: 'Family & Pixar 4K Animation Vault', quality: '4K UHD', genre: 'Kids & Family 4K', language: 'Multi-Audio', epg: false, bitrate: '28 Mbps', currentProgram: 'Toy Story & Frozen Complete 4K' },
      { id: 'vod-14', name: 'Standup Comedy Specials 2026', quality: 'FHD 60FPS', genre: 'Standup Specials', language: 'English', epg: false, bitrate: '14 Mbps', currentProgram: 'Netflix & HBO Comedy Specials' },
      { id: 'vod-15', name: 'True Crime & Netflix Docuseries', quality: '4K UHD', genre: 'Documentary Series', language: 'Multi-Sub', epg: false, bitrate: '24 Mbps', currentProgram: 'Making a Murderer & Planet Earth III' },
      { id: 'vod-16', name: 'Korean Dramas (K-Drama) Sub/Dub', quality: '4K UHD', genre: 'Asian Dramas', language: 'Korean/Multi', epg: false, bitrate: '22 Mbps', currentProgram: 'Squid Game & Crash Landing on You' },
      { id: 'vod-17', name: 'Anime Complete Series & Movies', quality: 'FHD 60FPS', genre: 'Japanese Anime', language: 'Japanese/English', epg: false, bitrate: '16 Mbps', currentProgram: 'Attack on Titan & Demon Slayer' },
      { id: 'vod-18', name: 'Turkish Dramas 4K (Dizi) Vault', quality: '4K UHD', genre: 'Turkish Telenovelas', language: 'Turkish/Multi', epg: false, bitrate: '20 Mbps', currentProgram: 'Kuruluş: Osman & Yargı' },
      { id: 'vod-19', name: 'French Cinema & Canal+ Series', quality: '4K UHD', genre: 'French Drama', language: 'French', epg: false, bitrate: '22 Mbps', currentProgram: 'Lupin & Le Bureau des Légendes' },
      { id: 'vod-20', name: 'Spanish Series & Movistar+ Originals', quality: '4K UHD', genre: 'Spanish Cinema', language: 'Spanish', epg: false, bitrate: '22 Mbps', currentProgram: 'Money Heist (La Casa de Papel) 4K' },
      { id: 'vod-21', name: 'Nordic Noir & Scandinavian Crime', quality: 'FHD 60FPS', genre: 'Nordic Drama', language: 'Nordic/Multi', epg: false, bitrate: '16 Mbps', currentProgram: 'The Bridge & Trapped Complete' },
      { id: 'vod-22', name: 'Arabic Cinema & Shahid VIP Series', quality: '4K UHD', genre: 'Arabic Hits', language: 'Arabic', epg: false, bitrate: '20 Mbps', currentProgram: 'Al Hayba & Ramadan Specials' },
      { id: 'vod-23', name: 'Bollywood & Indian Blockbusters', quality: '4K UHD', genre: 'Indian Cinema', language: 'Hindi/Tamil', epg: false, bitrate: '24 Mbps', currentProgram: 'RRR, Jawan & Pathaan 4K' },
      { id: 'vod-24', name: '4K Nature & BBC Wildlife 60FPS', quality: '4K UHD', genre: 'Nature Documentaries', language: 'English', epg: false, bitrate: '35 Mbps', currentProgram: 'Blue Planet II & Dynasties in 4K HDR' },
      { id: 'vod-25', name: 'Classic Hollywood Golden Era (1940-1970)', quality: 'FHD 60FPS', genre: 'Vintage Cinema', language: 'English', epg: false, bitrate: '14 Mbps', currentProgram: 'Casablanca & Citizen Kane Remastered' },
      { id: 'vod-26', name: 'Cinema 4K Classics 1980s & 1990s', quality: '4K UHD', genre: 'Retro Hits', language: 'English', epg: false, bitrate: '26 Mbps', currentProgram: 'Back to the Future & Jurassic Park 4K' },
      { id: 'vod-27', name: 'DC Extended Universe 4K Vault', quality: '4K UHD', genre: 'Comic Book Heroes', language: 'English', epg: false, bitrate: '30 Mbps', currentProgram: 'Zack Snyder\'s Justice League 4K' },
      { id: 'vod-28', name: 'Fast & Furious Complete 4K Saga', quality: '4K UHD', genre: 'Action Racing', language: 'Multi-Audio', epg: false, bitrate: '28 Mbps', currentProgram: 'Fast & Furious 1-10 4K HDR' },
      { id: 'vod-29', name: 'Harry Potter & Wizarding World 4K', quality: '4K UHD', genre: 'Fantasy Cinema', language: 'Multi-Audio', epg: false, bitrate: '30 Mbps', currentProgram: 'All 8 Films in 4K Dolby Vision' },
      { id: 'vod-30', name: 'Lord of the Rings Extended 4K', quality: '4K UHD', genre: 'Epic Fantasy', language: 'English', epg: false, bitrate: '35 Mbps', currentProgram: 'LOTR Extended Trilogy Remastered' },
      { id: 'vod-31', name: 'James Bond 007 Complete 4K Boxset', quality: '4K UHD', genre: 'Spy Action', language: 'English', epg: false, bitrate: '28 Mbps', currentProgram: 'All 25 Bond Movies in 4K' },
      { id: 'vod-32', name: 'Star Wars Complete Skywalker Saga', quality: '4K UHD', genre: 'Space Opera', language: 'Multi-Audio', epg: false, bitrate: '32 Mbps', currentProgram: 'Episodes I - IX in 4K HDR' },
      { id: 'vod-33', name: 'Quentin Tarantino Complete Films', quality: '4K UHD', genre: 'Cult Cinema', language: 'English', epg: false, bitrate: '28 Mbps', currentProgram: 'Kill Bill, Django & Inglorious Basterds' },
      { id: 'vod-34', name: 'Christopher Nolan 4K Cinema Vault', quality: '4K UHD', genre: 'Mind-Bending Sci-Fi', language: 'English', epg: false, bitrate: '35 Mbps', currentProgram: 'Oppenheimer, Inception & Interstellar' },
      { id: 'vod-35', name: 'Martin Scorsese Gangster Classics', quality: '4K UHD', genre: 'Crime Epics', language: 'English', epg: false, bitrate: '28 Mbps', currentProgram: 'Goodfellas, Casino & The Irishman' },
      { id: 'vod-36', name: 'Biographies & Historical Epics 4K', quality: '4K UHD', genre: 'History & Biopics', language: 'English', epg: false, bitrate: '26 Mbps', currentProgram: 'Napoleon, Gladiator & Braveheart' },
      { id: 'vod-37', name: 'Martial Arts & Bruce Lee / Jackie Chan', quality: 'FHD 60FPS', genre: 'Martial Arts Classics', language: 'Cantonese/English', epg: false, bitrate: '16 Mbps', currentProgram: 'Enter the Dragon & Police Story' },
      { id: 'vod-38', name: 'British Television Drama Boxsets', quality: 'FHD 60FPS', genre: 'BBC & ITV Masterpieces', language: 'English', epg: false, bitrate: '16 Mbps', currentProgram: 'Peaky Blinders & Downton Abbey' },
      { id: 'vod-39', name: 'Music Concerts & Festivals Live 4K', quality: '4K UHD', genre: 'Live Music & Festivals', language: 'English', epg: false, bitrate: '30 Mbps', currentProgram: 'Tomorrowland & Glastonbury 4K' },
      { id: 'vod-40', name: 'Kids 3D & 4K Family Cinema', quality: '4K UHD', genre: 'Family Fun', language: 'Multi-Audio', epg: false, bitrate: '26 Mbps', currentProgram: 'Despicable Me, Shrek & Minions' },
      { id: 'vod-41', name: 'Romantic Comedies & Valentine Vault', quality: 'FHD 60FPS', genre: 'Rom-Coms', language: 'English', epg: false, bitrate: '14 Mbps', currentProgram: 'Classic Rom-Com Hits' },
      { id: 'vod-42', name: 'War & Military Action 4K', quality: '4K UHD', genre: 'War Cinema', language: 'English', epg: false, bitrate: '30 Mbps', currentProgram: 'Saving Private Ryan & 1917 4K' },
      { id: 'vod-43', name: 'Post-Apocalyptic & Zombie Survival', quality: '4K UHD', genre: 'Survival Horror', language: 'English', epg: false, bitrate: '26 Mbps', currentProgram: '28 Days Later & World War Z' },
      { id: 'vod-44', name: 'Cyberpunk & Sci-Fi Dystopia 4K', quality: '4K UHD', genre: 'Sci-Fi Action', language: 'English', epg: false, bitrate: '32 Mbps', currentProgram: 'Blade Runner 2049 & Dune Part 1 & 2' },
      { id: 'vod-45', name: 'Sports Documentaries & 30 for 30', quality: 'FHD 60FPS', genre: 'Sports Stories', language: 'English', epg: false, bitrate: '16 Mbps', currentProgram: 'The Last Dance & Formula 1 Drive to Survive' },
      { id: 'vod-46', name: 'Mystery & Whodunnit Cinema', quality: '4K UHD', genre: 'Detective & Mystery', language: 'English', epg: false, bitrate: '25 Mbps', currentProgram: 'Knives Out & Glass Onion 4K' },
      { id: 'vod-47', name: 'Disaster & Survival Cinema 4K', quality: '4K UHD', genre: 'Disaster Movies', language: 'English', epg: false, bitrate: '28 Mbps', currentProgram: 'Twister, San Andreas & 2012' },
      { id: 'vod-48', name: 'Courtroom & Legal Dramas', quality: 'FHD 60FPS', genre: 'Legal Drama', language: 'English', epg: false, bitrate: '14 Mbps', currentProgram: 'A Few Good Men & Suits (Complete)' },
      { id: 'vod-49', name: 'Heist & Mastermind Cinema', quality: '4K UHD', genre: 'Crime Heist', language: 'English', epg: false, bitrate: '28 Mbps', currentProgram: 'Ocean\'s Eleven & Heat 4K' },
      { id: 'vod-50', name: 'Indie & Sundance Award Winners', quality: 'FHD 60FPS', genre: 'Independent Cinema', language: 'Multi-Audio', epg: false, bitrate: '16 Mbps', currentProgram: 'A24 Film Collection in HD' },
    ],
  },
  {
    slug: 'international',
    name: '24/7 International Feeds',
    title: 'Global Satellite Networks (Europe, LATAM, MENA & Asia)',
    tagline: 'Multi-Continent Coverage Spanning 100+ Countries in Full HD & 4K',
    description: 'Stream native broadcast television from France, Germany, Spain, Italy, Portugal, the Arab World, Latin America, Turkey, and Scandinavia with ultra-fast Anti-Freeze 9.0 servers.',
    count: '15,000+ Channels',
    iconName: 'Radio',
    badge: '100+ Countries Live',
    channels: [
      { id: 'int-1', name: 'TF1 HD France (Paris)', quality: 'FHD 60FPS', genre: 'French National Broadcast', language: 'French', epg: true, bitrate: '14 Mbps', currentProgram: 'Journal de 20 Heures' },
      { id: 'int-2', name: 'France 2, 3, 5 UHD', quality: '4K UHD', genre: 'French Public Television', language: 'French', epg: true, bitrate: '20 Mbps', currentProgram: 'Télématin & Documentaires' },
      { id: 'int-3', name: 'M6 & W9 HD France', quality: 'FHD 60FPS', genre: 'French Entertainment', language: 'French', epg: true, bitrate: '12 Mbps', currentProgram: 'Top Chef & Capital' },
      { id: 'int-4', name: 'Canal+ France 4K UHD', quality: '4K UHD', genre: 'French Cinema & Sports', language: 'French', epg: true, bitrate: '24 Mbps', currentProgram: 'Le Grand Journal & Ligue 1' },
      { id: 'int-5', name: 'Canal+ Cinéma & Séries HD', quality: 'FHD 60FPS', genre: 'French Movies & Series', language: 'French', epg: true, bitrate: '14 Mbps', currentProgram: 'Film Box Office' },
      { id: 'int-6', name: 'BeIN Sports 1-3 HD France', quality: 'FHD 60FPS', genre: 'French Live Sports', language: 'French', epg: true, bitrate: '15 Mbps', currentProgram: 'Football Ligue des Champions' },
      { id: 'int-7', name: 'RMC Sport 1 & 2 HD (FR)', quality: 'FHD 60FPS', genre: 'Combat & European Sports', language: 'French', epg: true, bitrate: '14 Mbps', currentProgram: 'UFC & MMA Live' },
      { id: 'int-8', name: 'BFM TV & CNews France HD', quality: 'HD', genre: '24/7 French News', language: 'French', epg: true, bitrate: '8 Mbps', currentProgram: 'Le Live BFM' },
      { id: 'int-9', name: 'La 1 & La 2 4K UHD (TVE Spain)', quality: '4K UHD', genre: 'Spanish National TV', language: 'Spanish', epg: true, bitrate: '22 Mbps', currentProgram: 'Telediario & Series' },
      { id: 'int-10', name: 'Antena 3 & La Sexta HD (ES)', quality: 'FHD 60FPS', genre: 'Spanish Entertainment & News', language: 'Spanish', epg: true, bitrate: '12 Mbps', currentProgram: 'El Hormiguero' },
      { id: 'int-11', name: 'Telecinco & Cuatro HD (ES)', quality: 'FHD 60FPS', genre: 'Spanish Reality & Dramas', language: 'Spanish', epg: true, bitrate: '12 Mbps', currentProgram: 'Supervivientes Live' },
      { id: 'int-12', name: 'Movistar Plus+ 4K (Spain)', quality: '4K UHD', genre: 'Spanish Cinema & Original Series', language: 'Spanish', epg: true, bitrate: '24 Mbps', currentProgram: 'Estreno Cine Movistar' },
      { id: 'int-13', name: 'Movistar LaLiga 4K UHD (ES)', quality: '4K UHD', genre: 'LaLiga EA Sports Live', language: 'Spanish', epg: true, bitrate: '25 Mbps', currentProgram: 'El Clásico En Directo' },
      { id: 'int-14', name: 'DAZN LaLiga 1-4 HD (ES)', quality: 'FHD 60FPS', genre: 'Spanish League Matchday', language: 'Spanish', epg: true, bitrate: '14 Mbps', currentProgram: 'LaLiga Matchday Live' },
      { id: 'int-15', name: 'Rai 1, Rai 2, Rai 3 4K (Italy)', quality: '4K UHD', genre: 'Italian National Network', language: 'Italian', epg: true, bitrate: '22 Mbps', currentProgram: 'TG1 & Sanremo Live' },
      { id: 'int-16', name: 'Canale 5, Italia 1, Rete 4 HD', quality: 'FHD 60FPS', genre: 'Mediaset Italy Entertainment', language: 'Italian', epg: true, bitrate: '12 Mbps', currentProgram: 'Grande Fratello & Cinema' },
      { id: 'int-17', name: 'Sky Sport Calcio & Uno HD (IT)', quality: 'FHD 60FPS', genre: 'Serie A & Champions League', language: 'Italian', epg: true, bitrate: '15 Mbps', currentProgram: 'Serie A TIM In Diretta' },
      { id: 'int-18', name: 'DAZN Serie A 1-5 HD (Italy)', quality: 'FHD 60FPS', genre: 'Full Italian Serie A Pass', language: 'Italian', epg: true, bitrate: '14 Mbps', currentProgram: 'Zona Serie A Live' },
      { id: 'int-19', name: 'Sky Cinema Uno & Due 4K (IT)', quality: '4K UHD', genre: 'Italian Cinema Premieres', language: 'Italian', epg: true, bitrate: '22 Mbps', currentProgram: 'Cinema Prima Fila' },
      { id: 'int-20', name: 'ARD Das Erste & ZDF 4K (DE)', quality: '4K UHD', genre: 'German National Broadcast', language: 'German', epg: true, bitrate: '22 Mbps', currentProgram: 'Tagesschau & Tatort' },
      { id: 'int-21', name: 'RTL, ProSieben & Sat.1 HD (DE)', quality: 'FHD 60FPS', genre: 'German Entertainment & Shows', language: 'German', epg: true, bitrate: '12 Mbps', currentProgram: 'Wer wird Millionär' },
      { id: 'int-22', name: 'Sky Sport Bundesliga 1-10 (DE)', quality: 'FHD 60FPS', genre: 'German Bundesliga Live', language: 'German', epg: true, bitrate: '15 Mbps', currentProgram: 'Bundesliga Konferenz' },
      { id: 'int-23', name: 'DAZN 1 & 2 HD Germany', quality: 'FHD 60FPS', genre: 'Bundesliga & UEFA Matchday', language: 'German', epg: true, bitrate: '14 Mbps', currentProgram: 'Freitagsspiel Live' },
      { id: 'int-24', name: 'Sky Cinema Premieren HD (DE)', quality: 'FHD 60FPS', genre: 'German Movie Premieres', language: 'German', epg: true, bitrate: '14 Mbps', currentProgram: 'Blockbuster Premiere' },
      { id: 'int-25', name: 'RTP 1 & RTP 2 HD (Portugal)', quality: 'FHD 60FPS', genre: 'Portuguese Public Broadcast', language: 'Portuguese', epg: true, bitrate: '12 Mbps', currentProgram: 'Telejornal RTP' },
      { id: 'int-26', name: 'SIC & TVI HD (Portugal)', quality: 'FHD 60FPS', genre: 'Portuguese Entertainment', language: 'Portuguese', epg: true, bitrate: '12 Mbps', currentProgram: 'Telenovelas & Jornal da Noite' },
      { id: 'int-27', name: 'Sport TV 1-6 HD (Portugal)', quality: 'FHD 60FPS', genre: 'Primeira Liga & Taça de Portugal', language: 'Portuguese', epg: true, bitrate: '15 Mbps', currentProgram: 'Benfica vs Porto Em Direto' },
      { id: 'int-28', name: 'Eleven Sports 1-6 HD (PT)', quality: 'FHD 60FPS', genre: 'Champions League Portugal', language: 'Portuguese', epg: true, bitrate: '14 Mbps', currentProgram: 'Champions League Noite' },
      { id: 'int-29', name: 'NPO 1, 2, 3 HD (Netherlands)', quality: 'FHD 60FPS', genre: 'Dutch Public Broadcaster', language: 'Dutch', epg: true, bitrate: '12 Mbps', currentProgram: 'NOS Journaal' },
      { id: 'int-30', name: 'RTL 4, 5, 7 & Veronica HD (NL)', quality: 'FHD 60FPS', genre: 'Dutch Commercial TV', language: 'Dutch', epg: true, bitrate: '12 Mbps', currentProgram: 'RTL Nieuws & Talkshow' },
      { id: 'int-31', name: 'Ziggo Sport Select 4K (NL)', quality: '4K UHD', genre: 'Dutch Sports & Formula 1', language: 'Dutch', epg: true, bitrate: '22 Mbps', currentProgram: 'Ziggo Sport Race Café' },
      { id: 'int-32', name: 'ESPN 1-4 HD Netherlands', quality: 'FHD 60FPS', genre: 'Dutch Eredivisie Live', language: 'Dutch', epg: true, bitrate: '14 Mbps', currentProgram: 'Eredivisie Live Match' },
      { id: 'int-33', name: 'VRT Eén & Canvas HD (Belgium)', quality: 'FHD 60FPS', genre: 'Belgian Flemish Television', language: 'Dutch', epg: true, bitrate: '12 Mbps', currentProgram: 'Het Journaal' },
      { id: 'int-34', name: 'RTL-TVI & La Une HD (Belgium)', quality: 'FHD 60FPS', genre: 'Belgian French TV', language: 'French', epg: true, bitrate: '12 Mbps', currentProgram: 'RTL Info 19h' },
      { id: 'int-35', name: 'MBC 1, MBC Drama, MBC Masr', quality: 'FHD 60FPS', genre: 'Pan-Arab Dramas & Shows', language: 'Arabic', epg: true, bitrate: '12 Mbps', currentProgram: 'Kalam El Nas & Mosalsalat' },
      { id: 'int-36', name: 'Shahid VIP Live Channels HD', quality: 'FHD 60FPS', genre: 'Exclusive Arabic Streaming', language: 'Arabic', epg: true, bitrate: '14 Mbps', currentProgram: 'Exclusive Arabic Series' },
      { id: 'int-37', name: 'Al Jazeera News HD (Arabic)', quality: 'HD', genre: '24/7 Middle East News', language: 'Arabic', epg: true, bitrate: '9 Mbps', currentProgram: 'Al Hasad News Live' },
      { id: 'int-38', name: 'Al Arabiya & Sky News Arabia', quality: 'HD', genre: 'Arab Breaking News', language: 'Arabic', epg: true, bitrate: '9 Mbps', currentProgram: 'Panorama Al Arabiya' },
      { id: 'int-39', name: 'BeIN Sports Premium 1-3 4K (MENA)', quality: '4K UHD', genre: 'AFC & African Champions League', language: 'Arabic', epg: true, bitrate: '24 Mbps', currentProgram: 'Studio Champions League' },
      { id: 'int-40', name: 'Rotana Cinema, Classic & Music', quality: 'HD', genre: 'Arabic Cinema Vault', language: 'Arabic', epg: true, bitrate: '9 Mbps', currentProgram: 'Classic Egyptian Cinema' },
      { id: 'int-41', name: 'Telemundo & Univision East (US)', quality: 'FHD 60FPS', genre: 'Latin America Live & Novelas', language: 'Spanish', epg: true, bitrate: '14 Mbps', currentProgram: 'Noticiero Univision' },
      { id: 'int-42', name: 'Las Estrellas & Azteca Uno (MX)', quality: 'FHD 60FPS', genre: 'Mexican National Television', language: 'Spanish', epg: true, bitrate: '12 Mbps', currentProgram: 'La Rosa de Guadalupe' },
      { id: 'int-43', name: 'TUDN HD USA & Mexico', quality: 'FHD 60FPS', genre: 'Liga MX & Soccer Live', language: 'Spanish', epg: true, bitrate: '14 Mbps', currentProgram: 'Liga MX En Vivo' },
      { id: 'int-44', name: 'TyC Sports HD (Argentina)', quality: 'FHD 60FPS', genre: 'Argentine Football & Sports', language: 'Spanish', epg: true, bitrate: '12 Mbps', currentProgram: 'Paso a Paso & Liga Profesional' },
      { id: 'int-45', name: 'Globo TV & Record HD (Brazil)', quality: 'FHD 60FPS', genre: 'Brazilian Television & Novelas', language: 'Portuguese', epg: true, bitrate: '14 Mbps', currentProgram: 'Jornal Nacional & Novela das Nove' },
      { id: 'int-46', name: 'SporTV 1, 2, 3 HD (Brazil)', quality: 'FHD 60FPS', genre: 'Brasileirão & Sports', language: 'Portuguese', epg: true, bitrate: '14 Mbps', currentProgram: 'Brasileirão Série A Ao Vivo' },
      { id: 'int-47', name: 'TRT 1, ATV & Kanal D (Turkey)', quality: 'FHD 60FPS', genre: 'Turkish National TV & Dizi', language: 'Turkish', epg: true, bitrate: '12 Mbps', currentProgram: 'Gönül Dağı & Ana Haber' },
      { id: 'int-48', name: 'BeIN Sports 1-4 HD Turkey', quality: 'FHD 60FPS', genre: 'Turkish Süper Lig Live', language: 'Turkish', epg: true, bitrate: '14 Mbps', currentProgram: 'Süper Lig Derbi Canlı' },
      { id: 'int-49', name: 'SVT 1 & 2 HD (Sweden)', quality: 'FHD 60FPS', genre: 'Swedish National Broadcast', language: 'Swedish', epg: true, bitrate: '12 Mbps', currentProgram: 'Rapport & Allsång' },
      { id: 'int-50', name: 'NRK 1 & 2 HD (Norway)', quality: 'FHD 60FPS', genre: 'Norwegian Public Television', language: 'Norwegian', epg: true, bitrate: '12 Mbps', currentProgram: 'Dagsrevyen' },
      { id: 'int-51', name: 'DR 1 & TV 2 HD (Denmark)', quality: 'FHD 60FPS', genre: 'Danish National Network', language: 'Danish', epg: true, bitrate: '12 Mbps', currentProgram: 'TV 2 Nyhederne' },
      { id: 'int-52', name: 'Polsat & TVP 1 HD (Poland)', quality: 'FHD 60FPS', genre: 'Polish National Broadcast', language: 'Polish', epg: true, bitrate: '12 Mbps', currentProgram: 'Wydarzenia & Ekstraklasa' },
    ],
  },
];

export function getCategoryBySlug(slug: string): ChannelCategory | undefined {
  return channelCategories.find((category) => category.slug === slug);
}